services:
  server:
    container_name: server
    depends_on:
      - tor-proxy
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
    command: rerun ruby app.rb
    tty: true
    networks:
      - network
    environment:
      REDIS_URL: redis://redis:6379/0

  tor-proxy:
    container_name: tor-proxy
    build:
      context: .
      dockerfile: Dockerfile.tor
    ports:
      - "9050:9050"
    networks:
      - network

  sidekiq:
    container_name: sidekiq
    depends_on:
      - server
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -r ./lib/vaquita/worker.rb
    volumes:
      - .:/usr/src/app
    networks:
      - network
    environment:
      REDIS_URL: redis://redis:6379/0

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
    driver: bridge
