FROM ruby:3.3.0

ENV RERUN_COLOR=false

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libtag1-dev \
    ffmpeg \    
    build-essential \
    wget \
    jq \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp && \
    chmod a+rx /usr/local/bin/yt-dlp

COPY . .

# Install any needed packages specified in Gemfile
RUN bundle install --with development

RUN gem install rerun

EXPOSE 4567

HEALTHCHECK CMD curl --fail http://youtube.com/ || exit 1

# Used for running tasks in this container
CMD ["tail", "-f", "/dev/null"]
